name: Node.js CI

on: [push]

jobs:
  build-node:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm install
        run: node app.js